name: E2E tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  e2e_tests:
    strategy:
      matrix:
        # ref: https://github.com/actions/runner-images
        os: [ubuntu-latest, macos-13, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.2' # The Go version to download (if necessary) and use.

      - name: build & install vfox (Unix-like)
        if: runner.os != 'Windows'
        run: |
          git clone https://github.com/version-fox/vfox.git
          cd vfox
          go build -o vfox
          chmod +x vfox
          cp vfox /usr/local/bin

      - name: build & install vfox (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/version-fox/vfox.git
          cd vfox
          go build -o vfox.exe
          echo "$pwd" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          ./vfox.exe -version

      - name: add vfox-mongo plugin
        run: |
          vfox add --source https://github.com/${{ github.repository_owner }}/vfox-mongo/archive/${GITHUB_REF}.zip mongo

      - name: install mongo server by vfox-mongo plugin (Linux)
        if: runner.os == 'Linux'
        run: |
          vfox install mongo@x86_64-ubuntu2004-8.0.0-rc0
          vfox use -g mongo@x86_64-ubuntu2004-8.0.0-rc0
          eval "$(vfox activate bash)"
          echo "===============PATH==============="
          echo $PATH
          echo "===============PATH==============="
          mongod --help

      - name: install mongo server by vfox-mongo plugin (Darwin)
        if: runner.os == 'MacOS'
        run: |
          vfox install mongo@macos-x86_64-7.3.1
          vfox use -g mongo@macos-x86_64-7.3.1
          echo "===============PATH==============="
          echo $PATH
          echo "===============PATH==============="
          eval "$(vfox activate bash)"
          mongod --help

      - name: install mongo server by vfox-mongo plugin (Windows)
        if: runner.os == 'Windows'
        run: |
          vfox install mongo@windows-x86_64-7.3.0
          vfox use -g mongo@windows-x86_64-7.3.0
          Invoke-Expression "$(vfox activate pwsh)"
          echo "===============PATH==============="
          echo $env:PATH
          echo "===============PATH==============="
          mongod --help