name: update_mongosh_versions

on:
  schedule:
    - cron: "0 16 * * 4"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update mongosh version file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd assets
          python3 -m pip install requests
          python3 get_all_mongosh_versions.py

      - name: Push updated version file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "chore(versions.txt): update mongosh version file"
            git push https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          else
            echo "never updated."
          fi
